name: Build and deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitHub Actions
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: mongorepositorycd.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        run: |
          docker build . -t mongorepositorycd.azurecr.io/mongorepository-cd:${{ github.sha }}
          docker push mongorepositorycd.azurecr.io/mongorepository-cd:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve publish profile for deployment
        id: publishProfileRetrieval
        run: |
          publishProfiles=$(az webapp deployment list-publishing-profiles \
            --name "MongoRepositoryService" \
            --resource-group "final-common-group" \
            --subscription "44b67705-3aeb-4405-8dcd-b8fba9fa2c3b" --xml)
          echo "::add-mask::$publishProfiles"
          echo "::set-output name=publishProfiles::$publishProfiles"

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MongoRepositoryService'
          images: 'mongorepositorycd.azurecr.io/mongorepository-cd:${{ github.sha }}'
          publish-profile: ${{ steps.publishProfileRetrieval.outputs.publishProfiles }}

      - name: Azure logout
        run: |
          az logout
